contents = [
'number sets' ,
'algebra' ,
'geometry' ,
'trigonometry' ,
'matrices and determinants' ,
'vectors' ,
'analytic geometry' ,
'differential calculus' ,
'integral calculus' ,
'differential equations' ,
'series' ,
'probability' 
]

subtopics = [ 
[ 'Set Identities' , 'Sets of Numbers' , 'Basic Identities' , 'Complex Numbers' ] , 
[ 'Factoring Formulas' , 'Product Formulas' , 'Powers' , 'Roots' , 'Logarithms' , 'Equations' , 'Inequalities' , 'Compound Interest Formulas' ] , 
[ 'Right Triangle' , 'Isosceles Triangle' , 'Equilateral Triangle' , 'Scalene Triangle' , 'Square' , 'Rectangle' , 'Parallelogram' , 'Rhombus' , 'Trapezoid' , 'Isosceles Trapezoid' , 'Isosceles Trapezoid with Inscribed Circle' , 'Trapezoid with Inscribed Circle' , 'Kite' , 'Cyclic Quadrilateral' , 'Tangential Quadrilateral' , 'General Quadrilateral' , 'Regular Hexagon' , 'Regular Polygon' , 'Circle' , 'Sector of a circle' , 'Segment of a circle' , 'Cube' , 'Rectangular Parallelepiped' , 'Prism' , 'Regular Tetrahedron' , 'Regular Pyramid' , 'Frustum of a Regular Pyramid' , 'Rectangular Right Wedge' , 'Platonic Solids' , 'Right Circular Cylinder' , 'Right Circular Cylinder with an Oblique Plane Face' , 'Right Circular Cone' , 'Frustum of a Right Circular Cone' , 'Sphere' , 'Spherical Cap' , 'Spherical Sector' , 'Spherical Segment' , 'Spherical Wedge' , 'Ellipsoid' , 'Circular Torus' ] , 
[ 'Radian and Degree Measures of Angles' , 'Definitions and Graphs of Trigonometric Functions' , 'Signs of Trignometric Functions' , 'Trigonometric Functions of common Angles' , 'Most Important Formulas' , 'Reduction formulas' , 'Periodicity of Trignometric Functions' , 'Relations between Trigonometric Functions' , 'Addition and Subtraction Formulas' , 'Double Angle Formulas' , 'Multiple Angle Formulas' , 'Half Angle Formulas' , 'Half Angle Tangent Identities' , 'Transforming of Trigonometric Expressions to Product' , 'Transforming of Trigonometric Expressions to Sum' , 'Powers of Trignometric Functions' , 'Graphs of Inverse Trignometric Functions' , 'Principle Values of Inverse Trigonometric Functions' , 'Relations between Inverse Trigonometric Functions' , 'Trigonometric Equations' , 'Relations to Hyperbolic Functions' ] , 
[ 'Determinants' , 'Properties of Determinants' , 'Matrices' , 'Operations with Matrices' , 'Systems of Linear Equations' ] , 
[ 'Vector Coordinates' , 'Vector Addition' , 'Vector Subtraction' , 'Scaling Vectors' , 'Scalar Product' , 'Vector Product' , 'Triple Product' ] , 
[ 'One -Dimensional Coordinate System' , 'Two -Dimensional Coordinate System' , 'Straight Line in Plane' , 'Circle' , 'Ellipse' , 'Hyperbola' , 'Parabola' , 'Three -Dimensional Coordinate System' , 'Plane' , 'Straight Line in Space' , 'Quadric Surfaces' , 'Sphere' ] ,
[ 'Functions and Their Graphs' , 'Limits of Functions' , 'Definitions and properties of the Derivative' , 'Table of Derivatives' , 'Higher Order Derivative' , 'Applications of Derivative' , 'Differential' , 'Multivariable Functions' , 'Differential Operators' ] , 
[ 'Indefinite Integral' , 'Integrals of Rational Functions' , 'Integrals of Irrational Functions' , 'Integrals of Trignometric Functions' , 'Integrals of Hyperbolic Functions' , 'Integrals of Exponential and Logarithmic Functions' , 'Reduction Formulas' , 'Definite Integral' , 'Improper Integral' , 'Double Integral' , 'Triple Integral' , 'Line Integral' , 'Surface Integral' ] , 
[ 'First Order Ordinary Differential Equations' , 'Second Order Ordinary Differential Equations' , 'Some Partial Differential Equations' ] , 
[ 'Arithmetic Series' , 'Geometric Series' , 'Some Finite Series' , 'Infinite Series' , 'Properties of Convergent Series' , 'Convergent Tests' , 'Alternating Series' , 'Power Series' , 'Differentiation and Integration of Power Series' , 'Taylor and Maclaurin Series' , 'Power Series Expansions for some Functions' , 'Binomial Series' , 'Fourier Series' ] , 
[ 'Permutations and Combinations' , 'Probability Formulas' ] 
]
    
titles = {
'1' : 'number sets' , 
'1.0' : 'Set Identities' , 
'1.1' : 'Sets of Numbers' , 
'1.2' : 'Basic Identities' , 
'1.3' : 'Complex Numbers' , 
'2' : 'algebra' , 
'2.0' : 'Factoring Formulas' , 
'2.1' : 'Product Formulas' , 
'2.2' : 'Powers' , 
'2.3' : 'Roots' , 
'2.4' : 'Logarithms' , 
'2.5' : 'Equations' , 
'2.6' : 'Inequalities' , 
'2.7' : 'Compound Interest Formulas' , 
'3' : 'geometry' , 
'3.0' : 'Right Triangle' , 
'3.1' : 'Isosceles Triangle' , 
'3.2' : 'Equilateral Triangle' , 
'3.3' : 'Scalene Triangle' , 
'3.4' : 'Square' , 
'3.5' : 'Rectangle' , 
'3.6' : 'Parallelogram' , 
'3.7' : 'Rhombus' , 
'3.8' : 'Trapezoid' , 
'3.9' : 'Isosceles Trapezoid' , 
'3.10' : 'Isosceles Trapezoid with Inscribed Circle' , 
'3.11' : 'Trapezoid with Inscribed Circle' , 
'3.12' : 'Kite' , 
'3.13' : 'Cyclic Quadrilateral' , 
'3.14' : 'Tangential Quadrilateral' , 
'3.15' : 'General Quadrilateral' , 
'3.16' : 'Regular Hexagon' , 
'3.17' : 'Regular Polygon' , 
'3.18' : 'Circle' , 
'3.19' : 'Sector of a circle' , 
'3.20' : 'Segment of a circle' , 
'3.21' : 'Cube' , 
'3.22' : 'Rectangular Parallelepiped' , 
'3.23' : 'Prism' , 
'3.24' : 'Regular Tetrahedron' , 
'3.25' : 'Regular Pyramid' , 
'3.26' : 'Frustum of a Regular Pyramid' , 
'3.27' : 'Rectangular Right Wedge' , 
'3.28' : 'Platonic Solids' , 
'3.29' : 'Right Circular Cylinder' , 
'3.30' : 'Right Circular Cylinder with an Oblique Plane Face' , 
'3.31' : 'Right Circular Cone' , 
'3.32' : 'Frustum of a Right Circular Cone' , 
'3.33' : 'Sphere' , 
'3.34' : 'Spherical Cap' , 
'3.35' : 'Spherical Sector' , 
'3.36' : 'Spherical Segment' , 
'3.37' : 'Spherical Wedge' , 
'3.38' : 'Ellipsoid' , 
'3.39' : 'Circular Torus' , 
'4' : 'trigonometry' , 
'4.0' : 'Radian and Degree Measures of Angles' , 
'4.1' : 'Definitions and Graphs of Trigonometric Functions' , 
'4.2' : 'Signs of Trignometric Functions' , 
'4.3' : 'Trigonometric Functions of common Angles' , 
'4.4' : 'Most Important Formulas' , 
'4.5' : 'Reduction formulas' , 
'4.6' : 'Periodicity of Trignometric Functions' , 
'4.7' : 'Relations between Trigonometric Functions' , 
'4.8' : 'Addition and Subtraction Formulas' , 
'4.9' : 'Double Angle Formulas' , 
'4.10' : 'Multiple Angle Formulas' , 
'4.11' : 'Half Angle Formulas' , 
'4.12' : 'Half Angle Tangent Identities' , 
'4.13' : 'Transforming of Trigonometric Expressions to Product' , 
'4.14' : 'Transforming of Trigonometric Expressions to Sum' , 
'4.15' : 'Powers of Trignometric Functions' , 
'4.16' : 'Graphs of Inverse Trignometric Functions' , 
'4.17' : 'Principle Values of Inverse Trigonometric Functions' , 
'4.18' : 'Relations between Inverse Trigonometric Functions' , 
'4.19' : 'Trigonometric Equations' , 
'4.20' : 'Relations to Hyperbolic Functions' , 
'5' : 'matrices and determinants' , 
'5.0' : 'Determinants' , 
'5.1' : 'Properties of Determinants' , 
'5.2' : 'Matrices' , 
'5.3' : 'Operations with Matrices' , 
'5.4' : 'Systems of Linear Equations' , 
'6' : 'vectors' , 
'6.0' : 'Vector Coordinates' , 
'6.1' : 'Vector Addition' , 
'6.2' : 'Vector Subtraction' , 
'6.3' : 'Scaling Vectors' , 
'6.4' : 'Scalar Product' , 
'6.5' : 'Vector Product' , 
'6.6' : 'Triple Product' , 
'7' : 'analytic geometry' , 
'7.0' : 'One -Dimensional Coordinate System' , 
'7.1' : 'Two -Dimensional Coordinate System' , 
'7.2' : 'Straight Line in Plane' , 
'7.3' : 'Circle' , 
'7.4' : 'Ellipse' , 
'7.5' : 'Hyperbola' , 
'7.6' : 'Parabola' , 
'7.7' : 'Three -Dimensional Coordinate System' , 
'7.8' : 'Plane' , 
'7.9' : 'Straight Line in Space' , 
'7.10' : 'Quadric Surfaces' , 
'7.11' : 'Sphere' , 
'8' : 'differential calculus' , 
'8.0' : 'Functions and Their Graphs' , 
'8.1' : 'Limits of Functions' , 
'8.2' : 'Definitions and properties of the Derivative' , 
'8.3' : 'Table of Derivatives' , 
'8.4' : 'Higher Order Derivative' , 
'8.5' : 'Applications of Derivative' , 
'8.6' : 'Differential' , 
'8.7' : 'Multivariable Functions' , 
'8.8' : 'Differential Operators' , 
'9' : 'integral calculus' , 
'9.0' : 'Indefinite Integral' , 
'9.1' : 'Integrals of Rational Functions' , 
'9.2' : 'Integrals of Irrational Functions' , 
'9.3' : 'Integrals of Trignometric Functions' , 
'9.4' : 'Integrals of Hyperbolic Functions' , 
'9.5' : 'Integrals of Exponential and Logarithmic Functions' , 
'9.6' : 'Reduction Formulas' , 
'9.7' : 'Definite Integral' , 
'9.8' : 'Improper Integral' , 
'9.9' : 'Double Integral' , 
'9.10' : 'Triple Integral' , 
'9.11' : 'Line Integral' , 
'9.12' : 'Surface Integral' , 
'10' : 'differential equations' , 
'10.0' : 'First Order Ordinary Differential Equations' , 
'10.1' : 'Second Order Ordinary Differential Equations' , 
'10.2' : 'Some Partial Differential Equations' , 
'11' : 'series' , 
'11.0' : 'Arithmetic Series' , 
'11.1' : 'Geometric Series' , 
'11.2' : 'Some Finite Series' , 
'11.3' : 'Infinite Series' , 
'11.4' : 'Properties of Convergent Series' , 
'11.5' : 'Convergent Tests' , 
'11.6' : 'Alternating Series' , 
'11.7' : 'Power Series' , 
'11.8' : 'Differentiation and Integration of Power Series' , 
'11.9' : 'Taylor and Maclaurin Series' , 
'11.10' : 'Power Series Expansions for some Functions' , 
'11.11' : 'Binomial Series' , 
'11.12' : 'Fourier Series' , 
'12' : 'probability' , 
'12.0' : 'Permutations and Combinations' ,  
'12.1' : 'Probability Formulas'
}
